### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by itemsCenter** [yuriti/obfuscation-tailwind#1]
hey would you please share how to use this plugin?

**Comment by yuriti** [comment]
Hello, I'm sorry, but I'm not yet ready to write instructions or confirm the reliability of this package. The package has been written for personal use, use it at your own risk.

At the moment I can tell you how I use it exactly:
1. include the package with version **0.0.2**: (package.json: `"obfuscation-tailwindcss": "0.0.2"`)
2. Add plugin connection to **nuxt.config.js**:
```
build: {
    plugins: [
        new ObfuscationTailwind({startsWithout: ['ad', 'rekl', 'banner']})
    ]
}
```
3. Plugin is ready to use!

the package may not support new versions of **vue3** or **tailwind3**
